# Generated by Django 5.0 on 2024-06-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_lawyer_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
